version: "3.5"

networks:
  securebin_network:
    name: securebin_network/securebin

services:
  backend:
    build: ./
    image: melzula/securebin
    container_name: securebin_backend
    ports:
      - "8080:8080"
    command: ./securebin
    networks:
      - securebin_network
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13.3
    ports:
      - 5445:5432
    volumes:
      - securebin_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=securebin
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=admin
    container_name: securebin_db
    networks:
      - securebin_network
    restart: on-failure

  web:
    image: nginx:latest
    networks:
      - securebin_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  securebin_db_data:
    name: securebin_db_data
